<a href="https://colab.research.google.com/github/AufanT/AufanTaufiqurrahman_2411532011_ML2526/blob/main/Praktikum3/TugasLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [16]:
dataset_url = 'https://raw.githubusercontent.com/AufanT/AufanTaufiqurrahman_2411532011_ML2526/refs/heads/main/Praktikum2/Breast_cancer_data.csv'
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=16)

In [18]:
logreg_unscaled = LogisticRegression(random_state=16, max_iter=10000)
logreg_unscaled.fit(X_train, y_train)
y_pred_unscaled = logreg_unscaled.predict(X_test)
acc_unscaled = accuracy_score(y_test, y_pred_unscaled)

In [19]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
logreg_scaled = LogisticRegression(random_state=16)
logreg_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = logreg_scaled.predict(X_test_scaled)
acc_scaled = accuracy_score(y_test, y_pred_scaled)

In [21]:
print(f"--- Perbandingan Kinerja (Scaling vs Tanpa Scaling) ---")
print(f"Akurasi TANPA Scaling: {acc_unscaled:.4f}")
print(f"Akurasi DENGAN Scaling: {acc_scaled:.4f}\n")

--- Perbandingan Kinerja (Scaling vs Tanpa Scaling) ---
Akurasi TANPA Scaling: 0.9357
Akurasi DENGAN Scaling: 0.9649



In [22]:
y_pred_proba = logreg_scaled.predict_proba(X_test_scaled)[:, 1]

In [23]:
thresholds = [0.3, 0.5, 0.7]

In [24]:
print("--- Evaluasi Pengaruh Threshold ---")
for thresh in thresholds:
    # Mengubah probabilitas menjadi kelas 0 atau 1 berdasarkan threshold
    y_pred_custom = (y_pred_proba >= thresh).astype(int)

    print(f"\n[ Threshold = {thresh} ]")
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_custom))
    print("\nClassification Report:\n", classification_report(y_test, y_pred_custom))

--- Evaluasi Pengaruh Threshold ---

[ Threshold = 0.3 ]

Confusion Matrix:
 [[ 58   7]
 [  0 106]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.89      0.94        65
           1       0.94      1.00      0.97       106

    accuracy                           0.96       171
   macro avg       0.97      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171


[ Threshold = 0.5 ]

Confusion Matrix:
 [[ 61   4]
 [  2 104]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.94      0.95        65
           1       0.96      0.98      0.97       106

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171


[ Threshold = 0.7 ]

Confusion Matrix:
 [[ 62   3]
 [  4 102]]

Classification Report:
               precision    recall  f1-score